#!/bin/bash

runtest() {
  output=$(cargo run "$1")
  if [ "$output" != "$2" ]; then
    echo "$1: $2 expected. but got $output"
    exit 1
  fi
  echo "$1 => $output"
}

runtest 0 0
runtest 1 1
runtest 21 21
runtest 5555 5555
runtest '+ 1 1' '2'
runtest '+ 10 21' '31'
