#!/bin/bash

cargo build || exit 1

runtest() {
  output=$(RUST_BACKTRACE=1 ./target/debug/lang "$1")
  if [ "$output" != "$2" ]; then
    echo "$1: $2 expected. but got $output"
    exit 1
  fi
  echo "$1 => $output"
}

runtest 0 0
runtest 1 1
runtest 21 21
runtest 5555 5555
runtest '+ 1
2' 3

echo '=== arithmetic operators ==='

runtest '+ 1 1' '2'
runtest '+ 10 21' '31'
runtest '* 3 5' '15'
runtest '- 5 1' '4'
runtest '/ 4 2' '2'
runtest '+ + + 1 + 2 3 4 5' '15'
runtest '+ 2 *4 3' '14'

echo '=== functions ==='
runtest 'F[+ a a ] + 1 2' 3

runtest 'F[+ a a ] F(1)' 2
runtest 'F[* a 2 ] F(5)' 10
runtest 'F[* a a ] F(F(2))' 16
runtest 'F[/ a a ] F(F(3))' 1
runtest 'F[G(a)] G[+ a a] F(2)' 4
runtest 'F[+ a a] + F(2) F(3) ' 10
runtest 'F[+ a b] + F(2 3) F(3 4) ' 12
runtest 'F[- a b] F( F(6 2) F(5 3) )' 2

echo '=== built-in function==='
runtest 'P(5)' '5
5'

echo OK
